spring:
  application:
    name: foo-service
  sleuth:
    sampler:
      # by default 10% of requests are sampled, here we say sample all requests
      percentage: 1.0
    zuul:
       enabled: true

zuul:
  routes:
    proxy:
      url: http://localhost:8081
